name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # This triggers the deployment when PRs are merged into main
  pull_request:
    branches: [ "main" ]  # This triggers the CI for PRs


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          # Make sure you're in the repository root
          ls -R  # (Optional) Debug listing of all files/folders
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          # Next line ensures app/ is on the Python path
          export PYTHONPATH=.
          pytest tests

      - name: Build Docker Image
        run: |
          docker build -t devops_project:ci-test .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Only run deploy if CI passes
    if: github.ref == 'refs/heads/main'  # Run deploy only on the main branch
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      
      - name: Set up SSH
      
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # Using SSH key from GitHub Secrets


      - name: Login to container registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io
        
      - name: Build and push Docker image
        run: |
          docker build -t sandy283/devops_project:latest .
          docker push sandy283/devops_project:latest

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} ubuntu@${{ secrets.AWS_EC2_IP }} "docker pull sandy283/devops_project:latest && docker-compose up -d"